/**
 * Layout regression test for the running text of every theme.
 *
 * Themes like to tighten the gap under a heading by giving the heading a
 * negative bottom margin. That pulls the block below it upwards. For plain text
 * the move is invisible, because the glyphs sit inside the line's leading, so
 * the mistake survives every screenshot of ordinary prose. Anything that paints
 * a background - a button from the Link Buttons plugin, an image, a code block -
 * has no leading to hide in and lands on top of the heading's own words.
 *
 * A second trap sits next to the first: `.x-prose p { margin: 0 }` outweighs the
 * block rhythm `.x-prose > * + *`, because a class plus a type selector beats a
 * class plus two universals. Paragraphs then have no gap between them at all.
 *
 * Both faults are pure geometry, so they are checked as geometry: the gap
 * between neighbouring blocks must never be negative, consecutive paragraphs
 * must actually be separated, and nothing with a background may overlap text it
 * does not own.
 *
 * Run inside the Typemill Docker container:
 *   npm run test:browser
 */
import puppeteer from 'puppeteer'
import { readFileSync, writeFileSync, unlinkSync, existsSync, readdirSync, rmSync } from 'node:fs'
import { join } from 'node:path'

const BASE_URL = process.env.TM_BASE_URL || 'http://127.0.0.1:8080'
const TM_ROOT = process.env.TM_ROOT || '/var/www/html'

const SETTINGS_FILE = join(TM_ROOT, 'settings', 'settings.yaml')
const CONTENT_DIR = join(TM_ROOT, 'content')
const THEMES_DIR = join(TM_ROOT, 'themes')
const NAV_CACHE = join(TM_ROOT, 'data', 'navigation')

// Typemill reads the segment before the first dash as a sort prefix and drops
// it from the URL, so the file name and the path are deliberately different.
const FIXTURE_SLUG = '98-theme-prose-fixture'
const FIXTURE_URL = '/theme-prose-fixture'

/**
 * Headings followed by different kinds of block, plus buttons sitting inline in
 * running text, in a list and in a quote. `[[label](url)]` is the Link Buttons
 * syntax; without that plugin the brackets stay literal and the button checks
 * simply find nothing to measure.
 */
const FIXTURE_MARKDOWN = `# Theme prose fixture

An opening paragraph of running text.

A second paragraph, which must not sit flush against the first one.

## Heading followed by a button

[[Download](https://example.com/)]

A paragraph under the button.

### Sub heading followed by a button

[[View on GitHub](https://example.com/)]

Another paragraph.

### Sub heading followed by plain text

Text that follows a heading directly.

### Sub heading followed by a code block

\`\`\`
code that paints a background
\`\`\`

A paragraph with a button [[Docs](https://example.com/)] in the middle of the
sentence, followed by enough words to wrap the line and prove that the box does
not touch the line above or the line below it.

* A list item with a button [[Source](https://example.com/)]
* A plain list item

> A quote with a button [[Read](https://example.com/)] inside it.

A closing paragraph.
`

function assert(condition, message) {
    if (!condition) {
        throw new Error(message)
    }
}

function listThemes() {
    return readdirSync(THEMES_DIR, { withFileTypes: true })
        .filter((entry) => entry.isDirectory())
        .map((entry) => entry.name)
        .sort()
}

function setTheme(name) {
    const content = readFileSync(SETTINGS_FILE, 'utf8')
    const next = /^theme:.*$/m.test(content)
        ? content.replace(/^theme:.*$/m, `theme: ${name}`)
        : `theme: ${name}\n${content}`
    writeFileSync(SETTINGS_FILE, next)
}

function clearNavigationCache() {
    // The navigation is cached, so a freshly written page is otherwise a 404.
    if (!existsSync(NAV_CACHE)) {
        return
    }
    for (const entry of readdirSync(NAV_CACHE)) {
        rmSync(join(NAV_CACHE, entry), { force: true, recursive: true })
    }
}

function writeFixture() {
    writeFileSync(join(CONTENT_DIR, `${FIXTURE_SLUG}.md`), FIXTURE_MARKDOWN)
    writeFileSync(
        join(CONTENT_DIR, `${FIXTURE_SLUG}.yaml`),
        'meta:\n    title: \'Theme prose fixture\'\n    hide: true\n    noindex: true\n'
    )
    clearNavigationCache()
}

function removeFixture() {
    for (const ext of ['md', 'yaml', 'txt']) {
        const file = join(CONTENT_DIR, `${FIXTURE_SLUG}.${ext}`)
        if (existsSync(file)) {
            unlinkSync(file)
        }
    }
    clearNavigationCache()
}

/**
 * Measure the rendered article.
 *
 * The prose container is found from the content itself rather than from a
 * per-theme class name: the fixture's headings are generated by Markdown, so
 * whatever element holds them is the running-text container.
 */
function measure() {
    const headings = Array.from(document.querySelectorAll('h2, h3'))
    if (headings.length === 0) {
        return { error: 'no headings found - did the fixture page render?' }
    }

    // The container that holds the most of the fixture's headings.
    const counts = new Map()
    for (const heading of headings) {
        const parent = heading.parentElement
        if (!parent) continue
        counts.set(parent, (counts.get(parent) || 0) + 1)
    }
    let root = null
    let best = 0
    for (const [element, count] of counts) {
        if (count > best) {
            best = count
            root = element
        }
    }
    if (!root) {
        return { error: 'could not resolve the prose container' }
    }

    const describe = (element) => {
        const label = (element.textContent || '').trim().replace(/\s+/g, ' ').slice(0, 32)
        return `${element.tagName.toLowerCase()}${label ? ` "${label}"` : ''}`
    }

    const negativeGaps = []
    const paragraphGaps = []
    const blocks = Array.from(root.children)

    for (let i = 1; i < blocks.length; i += 1) {
        const previous = blocks[i - 1]
        const current = blocks[i]
        const previousRect = previous.getBoundingClientRect()
        const currentRect = current.getBoundingClientRect()

        // Elements taken out of flow cannot be measured this way.
        const position = getComputedStyle(current).position
        if (position === 'absolute' || position === 'fixed') continue
        if (previousRect.height === 0 || currentRect.height === 0) continue

        const gap = Number((currentRect.top - previousRect.bottom).toFixed(2))

        if (gap < 0) {
            negativeGaps.push({ pair: `${describe(previous)} -> ${describe(current)}`, gap })
        }
        if (previous.tagName === 'P' && current.tagName === 'P') {
            paragraphGaps.push(gap)
        }
    }

    // Boxes that paint a background must not cover text they do not own.
    const painted = Array.from(root.querySelectorAll('.link-button'))
    const collisions = []

    if (painted.length > 0) {
        const isVisible = (node) => {
            let element = node.parentElement
            while (element) {
                const style = getComputedStyle(element)
                if (
                    style.visibility === 'hidden'
                    || style.display === 'none'
                    || style.opacity === '0'
                    || element.hasAttribute('hidden')
                ) {
                    return false
                }
                element = element.parentElement
            }
            return true
        }

        const textRects = []
        const walker = document.createTreeWalker(root, NodeFilter.SHOW_TEXT)
        let node = walker.nextNode()
        while (node) {
            const text = node.textContent.trim()
            const ownedByButton = painted.some((button) => button.contains(node))
            if (text && !ownedByButton && isVisible(node)) {
                const range = document.createRange()
                range.selectNodeContents(node)
                for (const rect of range.getClientRects()) {
                    if (rect.width > 1 && rect.height > 1) {
                        textRects.push({ rect, text: text.slice(0, 32) })
                    }
                }
            }
            node = walker.nextNode()
        }

        for (const button of painted) {
            const buttonRect = button.getBoundingClientRect()
            for (const candidate of textRects) {
                const overlapY = Math.min(buttonRect.bottom, candidate.rect.bottom)
                    - Math.max(buttonRect.top, candidate.rect.top)
                const overlapX = Math.min(buttonRect.right, candidate.rect.right)
                    - Math.max(buttonRect.left, candidate.rect.left)
                // A hairline touch is rounding, not a collision.
                if (overlapY > 1.5 && overlapX > 1.5) {
                    collisions.push({
                        button: (button.textContent || '').trim().slice(0, 24),
                        covers: candidate.text,
                        by: Number(overlapY.toFixed(2)),
                    })
                }
            }
        }
    }

    return {
        container: root.className || root.tagName.toLowerCase(),
        buttons: painted.length,
        negativeGaps,
        paragraphGaps,
        collisions,
    }
}

async function assertThemeProse(page, theme, widths) {
    for (const width of widths) {
        await page.setViewport({ width, height: 1200 })
        await page.goto(`${BASE_URL}${FIXTURE_URL}`, { waitUntil: 'networkidle2' })

        const result = await page.evaluate(measure)
        assert(!result.error, `${theme} @${width}px: ${result.error}`)

        assert(
            result.negativeGaps.length === 0,
            `${theme} @${width}px: a block is pulled over the one above it, so anything `
                + `with a background will overlap it:\n`
                + result.negativeGaps.map((entry) => `  ${entry.pair} gap ${entry.gap}px`).join('\n')
        )

        assert(
            result.paragraphGaps.length > 0,
            `${theme} @${width}px: the fixture rendered no consecutive paragraphs to measure`
        )
        const flush = result.paragraphGaps.filter((gap) => gap <= 0)
        assert(
            flush.length === 0,
            `${theme} @${width}px: ${flush.length} of ${result.paragraphGaps.length} paragraph `
                + `pairs sit flush against each other (gaps: ${result.paragraphGaps.join(', ')}px). `
                + `A 'prose p { margin: 0 }' rule outweighs the block rhythm.`
        )

        assert(
            result.collisions.length === 0,
            `${theme} @${width}px: a button covers text that is not its own:\n`
                + result.collisions
                    .map((hit) => `  "${hit.button}" covers "${hit.covers}" by ${hit.by}px`)
                    .join('\n')
        )
    }
}

async function main() {
    if (!existsSync(SETTINGS_FILE)) {
        console.error(`settings.yaml not found at ${SETTINGS_FILE}; run npm run test:setup first`)
        process.exit(1)
    }

    const originalSettings = readFileSync(SETTINGS_FILE, 'utf8')
    const themes = listThemes()
    assert(themes.length > 0, `no themes found in ${THEMES_DIR}`)

    const launchOptions = {
        headless: true,
        args: ['--no-sandbox', '--disable-setuid-sandbox', '--disable-dev-shm-usage'],
    }
    if (process.env.PUPPETEER_EXECUTABLE_PATH) {
        launchOptions.executablePath = process.env.PUPPETEER_EXECUTABLE_PATH
    }

    writeFixture()
    const browser = await puppeteer.launch(launchOptions)

    try {
        const page = await browser.newPage()
        let buttonsSeen = 0

        for (const theme of themes) {
            setTheme(theme)
            await assertThemeProse(page, theme, [1280, 900, 600, 390])

            const buttons = await page.evaluate(() => document.querySelectorAll('.link-button').length)
            buttonsSeen += buttons
            console.log(`ok: theme prose (${theme}${buttons ? `, ${buttons} buttons` : ''})`)
        }

        if (buttonsSeen === 0) {
            console.log(
                'note: the Link Buttons plugin is inactive, so only the block gaps were checked'
            )
        }
    } finally {
        await browser.close()
        writeFileSync(SETTINGS_FILE, originalSettings)
        removeFixture()
    }
}

main().catch((error) => {
    console.error(error.message || error)
    process.exit(1)
})
